### ISSUE TITLE
Ongoing memory usage problem 

### ISSUE THREAD

**Issue by JoanMVPopov** [JoanMVPopov/HeltiBot#1]
The current state of this app requires Heroku to carry a heavy load when it comes to memory. 
The amount of data stored in memory causes constant **R14 errors** (tracked through Papertail add-on and Heroku CLI).

After some testing (commit 1af0bf68), the root cause of the problem is believed to be the implementation of the Classla NLP library.
Therefore, the library and its respective external required files ought to be offloaded to another cloud platform that could host endpoints for inference

My current solution is to use Amazon SageMaker, updates will be posted soon

**Comment by zakrok** [comment]
# Absolute loser

**Comment by JoanMVPopov** [comment]
The issue has been **RESOLVED**

_SOLUTION:_
1) **Amazon SageMaker** did not help in this case, as the platform required a different workflow (using custom Docker containers and different APIs for invocation, which is not feasible for me at the moment) and a more thorough file structure in order to host an endpoint. 
2) After researching different kinds of services, I stumbled upon a _FaaS (Function as a Service)_ platform - **Google Cloud**.
Their **Cloud Functions** service was just what I needed, since they provide you with a very straightforward function builder which can be customized to suit your needs. 
3) After creating my function, I downloaded the classla models through the function instance and saved them in a temp folder (Special thanks to https://stackoverflow.com/questions/51308489/google-clould-functions-deploy-erofs-read-only-file-system)

Along with some additional steps, this is how I was able to solve this issue :)
